### ISSUE TITLE
Current App version doesn't save tractometry results

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/app-tractseg#10]
The current App version doesn't save tractometry results. I'd like to save it, however the output file Tractometry_subject1.csv does not comply with the definition of the neuro/tractmeasures datatype in BL. Options:
* convert it to be compliant with the existing datatype, and assign the datatype tag `tractseg`
* create a new datatype, e.g. tractseg/tractmeasures (and possibly an App to convert it to the neuro/tractmeasures datatype)
Both versions could also be saved as output.

**Comment by soichih** [comment]
We've registered a new datatype to store various tractseg output (https://brainlife.io/datatype/630d072219b13f0a0ee3cd15) @giulia-berto Please update the description / README. 

@giulia-berto is going to write an App similar to Freesurfer Group Analysis (https://brainlife.io/app/5b7f0f89b3e3800027ce9b6c) which will take multiple tractseg outputs and create the grouped tract measures.

**Comment by giulia-berto** [comment]
Resolved here: https://github.com/brainlife/app-tractseg/pull/15
