### ISSUE TITLE
csd_msmt_5tt doesn't work without T1 input

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/app-tractseg#11]
My guess is that cds_type=csd_msmt_5tt doesn't work without T1 input. Should we make the T1 input optional?

**Comment by soichih** [comment]
Oh I never knew that csd_msmt_5tt required t1. If that is the case, yes we should add t1 as an optional input. Does it have to be aligned to dwi though?

**Comment by giulia-berto** [comment]
Resolved here: https://github.com/brainlife/app-tractseg/pull/15
