### ISSUE TITLE
"...T1w_acpc_dc_restore_brain.nii.gz": No such file or directory

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/app-tractseg#8]
Error encountered in recent run.  Relevant error log as follows:

> 5ttgen: Generated scratch directory: /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/5ttgen-tmp-P87329/
mrinfo: [ERROR] cannot access file "/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/T1w_acpc_dc_restore_brain.nii.gz": No such file or directory
mrinfo: [ERROR] error opening image "/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/T1w_acpc_dc_restore_brain.nii.gz"

>5ttgen: [ERROR] Could not access header information for image '/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/T1w_acpc_dc_restore_brain.nii.gz'
dwi2response: 
dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
dwi2response: 
dwi2response: Generated scratch directory: /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/dwi2response-tmp-8553ZP/
dwi2response: Importing DWI data (/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/dwi.nii.gz)...
dwi2response: Importing mask (/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/tractseg_output/nodif_brain_mask.nii.gz)...
Command:  mrconvert /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/tractseg_output/5TT.nii.gz /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/dwi2response-tmp-8553ZP/5tt.mif

>dwi2response: [ERROR] mrconvert /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/tractseg_output/5TT.nii.gz /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/dwi2response-tmp-8553ZP/5tt.mif (msmt_5tt.py:53)
dwi2response: [ERROR] Information from failed command:
dwi2response:
              mrconvert: [ERROR] cannot access file "/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/tractseg_output/5TT.nii.gz": No such file or directory
              mrconvert: [ERROR] error opening image "/ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/tractseg_output/5TT.nii.gz"
dwi2response:
dwi2response: [ERROR] For debugging, inspect contents of scratch directory: /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/dwi2response-tmp-8553ZP/
dwi2response: Scratch directory retained; location: /ocean/projects/dbs190008p/shayashi/prod/60495e1e2541c128a79b65f5/604a83fb7503892d3fe6166d/dwi2response-tmp-8553ZP/
===========]
dwi2fod: [ERROR] Unable to open numerical data text file "tractseg_output/RF_WM.txt": No such file or directory
dwi2fod: [ERROR] File "tractseg_output/RF_WM.txt" is not a valid response function file
dwi2fod: [ERROR] MSMT_CSD algorithm expects the first file in each argument pair to be an input response function file
sh2peaks: [ERROR] cannot access file "tractseg_output/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tractseg_output/peaks.nii.gz'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 417, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 255, in main
    data_img = nib.load(peak_path)
  File "/usr/local/lib/python3.7/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'

>real	13m31.503s
user	10m15.669s
sys	0m28.295s

Let me know if any additional information would be of use

**Comment by giulia-berto** [comment]
Hi, I found this issue only now that I'm experiencing the same error myself. This seems rather a problem of TractSeg which apparently calls an MRtrix3 function, see also this issue https://github.com/MIC-DKFZ/TractSeg/issues/106. What worked in my case was to use `--csd_type csd` instead of `--csd_type csd_msmt_5tt`. I'll probably update the BL App to use TractSeg v2.5 to see if the error still persists.
