### ISSUE TITLE
Expose --nr_fibers variable on brainlife interface

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/app-tractseg#9]
https://github.com/MIC-DKFZ/TractSeg/blob/ffc0c933824d92fe09e22d8f56e8541ec4ed9f5e/bin/Tracking#L76-L77

Would it be possible to add a mechanism to specify the requested number of fibers?  The default of 2000 is actually kind of low, particularly for tracts that have wide fanning (e.g CST).  I worry that, given the current setup of Brainlife / apps, this might require the creation of an entirely new app, but hopefully there's a less drastic way of achieving this.

**Comment by DanNBullock** [comment]
Maybe also somehow find a way to expose some sort of parameter for inter-node distance in streamlines?  I couldn't find one in my exploration of their code, however, a quick check of an example AF_left from tractSeg had 2000 streamlines with an average of ~35 nodes.  

That's super sparse sampling!  In some cases the inter-node distance was as much as 8 or more mm (suggesting that they are doing adaptive node spacing).  This can cause all kinds of downstream problems with subsequent visualization or analysis.  For example, this would cause problems for [DIPY's density map function](https://github.com/dipy/dipy/blob/f0775487bf01eee8964f5224e176ec99c891da0e/dipy/tracking/utils.py#L67-L107) and my visualization functions' attempts to dynamically alter color streamline color mappings based on anatomical characteristics.

One option would be to target tractSeg's use of mrtrix and try and inject the `-step` parameter into its use of `tckgen` but I'm not sure how viable that would be.  Alternatively, [DIPY has a method to resample to a set number of nodes for a collection of streamlines](https://github.com/dipy/dipy/blob/master/dipy/tracking/streamlinespeed.pyx), which is admittedly kind of clunky, relative to the hypothetical alternative of specifying a target inter-node distance.

**Comment by giulia-berto** [comment]
RE: expose --nr_fibers. This cannot be easily done unfortunately since that parameter it's embedded in the TractSeg docker. As you noticed, this would require creating a new App and more importantly a new docker container.

RE: inter-node distance. As far as I remember, they are compressing the streamlines using this function: https://dipy.org/documentation/1.4.1./reference/dipy.tracking/#compress-streamlines. So yes, the step size in some cases can be up to 10 mm.

**Comment by giulia-berto** [comment]
However, you may try to use this App to resample the tck file with a different step size: https://doi.org/10.25663/brainlife.app.124.

**Comment by DanNBullock** [comment]
Resolved here: https://github.com/brainlife/app-tractseg/pull/15
